pr: none
trigger: none

variables: 
- group: capstone_mlops_vg

stages:
- stage: 'Dev'
  displayName: 'Dev'
  jobs:
  - job: 'Provision_Dev'
    displayName: 'Provision Dev resources'
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        action: 'Create or update resource group'
        resourceGroupName: '$(RESOURCE_GROUP)'
        location: '$(LOCATION)'
        templatelocation: 'Linked artifact'
        #csmfile: '$(Build.SourceDirectory)'/environment_setup/cloud-environment.json'
        overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION) -workspace $(WORKSPACE_NAME)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy resources to Azure'

